# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '73b32e2b-0ea9-4779-90cd-70b308f16822'
  imageRepository: 'manjuwithaks'
  containerRegistry: 'sampledemo.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'sampledemo83b9-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: CQA
  displayName: CQA stage
  jobs:
  - job: CQA
    displayName: CQA
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: SonarQubePrepare@8
      inputs:
        SonarQube: 'aks-sonarqube'
        scannerMode: 'other'
    - task: Maven@4
      displayName: 'Build and Analyze'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '21'
        jdkArchitectureOption: 'x64'
        sonarQubeRunAnalysis: true
        options: '-X -Dsonar.verbose=true'
    - task: SonarQubePublish@8
      inputs:
        pollingTimeoutSec: '300'

- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        command: 'build'
        Dockerfile: '**/Dockerfile'
        arguments: |
          --no-cache
          -t $(containerRegistry)/$(imageRepository):$(tag)
          -t $(containerRegistry)/$(imageRepository):latest
    - script: |
        docker images 
      displayName: List Docker images
    - script: |
        sudo apt-get install wget gnupg
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy
      displayName: Install Trivy
    - script: |
        trivy image \
          --severity HIGH,CRITICAL \
          --exit-code 1 \
          --no-progress \
          $(containerRegistry)/$(imageRepository):$(tag)
      displayName: Trivy Security Scan
    - task: Docker@2
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        command: 'push'
        tags: '$(tag);latest'
    - upload: manifests
      artifact: manifests

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'manju9676withAKS.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)

