# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '73b32e2b-0ea9-4779-90cd-70b308f16822'
  imageRepository: 'manjuwithaks'
  containerRegistry: 'sampledemo.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'sampledemo83b9-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: CQA
  displayName: CQA stage
  jobs:
  - job: CQA
    displayName: CQA
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '21'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'AzurePipeline'
    - task: SonarQubePrepare@8
      inputs:
        SonarQube: 'aks-sonarqube'
        scannerMode: 'Other'
        extraProperties: |
          sonar.login=$(SONAR_TOKEN)
          sonar.java.binaries=target/classes
    - script: mvn -B -Dmaven.test.skip=false clean verify sonar:sonar -Dsonar.login=$(SONAR_TOKEN)
      displayName: 'Run Maven build and SonarQube analysis'
    - task: SonarQubePublish@8
      inputs:
        pollingTimeoutSec: '300'

- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - upload: manifests
      artifact: manifests

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'manju9676withAKS.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)

