# SonarQube project properties
sonar.projectKey=sample-webapp
sonar.projectName=sample-webapp
sonar.projectVersion=1.0

# Path to sources
sonar.sources=src/main/java,src/main/webapp

# Encoding
sonar.sourceEncoding=UTF-8
